---
- name: Check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping hosts
      win_ping:
      register: ping_result
      ignore_errors: yes

    - name: Group by reachable hosts
      group_by:
        key: reachable
      when: ping_result is success


- name: Mount, execute a command, and unmount a drive on Windows hosts
  hosts: reachable
  gather_facts: no
  tasks:
    - name: Mount the network drive Z
      win_mount:
      path: Z:
      src: '\\ptmvm02\Deployment\hinventoryWindows'
      state: present

    #- name: Execute a command
    #  win_command: your_command_here
    #  # Ersetze 'your_command_here' mit dem tatsächlichen Befehl, den du ausführen möchtest

    - name: Remove the network drive Z
      win_mount:
        path: Z:
        state: absent
