---
- name: Check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping hosts
      win_ping:
      register: ping_result
      ignore_errors: yes

    - name: Group by reachable hosts
      group_by:
        key: reachable
      when: ping_result is success

- name: Create a mapped drive under Z
  hosts: reachable
  gather_facts: no
  community.windows.win_mapped_drive:
    letter: Z
    path: \\ptmvm02\Deployment\hinventoryWindows
      
- name: Ausführen von H-Inventory auf Windows-Servern
  hosts: reachable
  gather_facts: no
  tasks:
    - name: H-Inventory ausführen
      win_shell: '\\ptmvm02\Deployment\hinventoryWindows\scan.bat'

- name: Delete any mapped drives under Z
  hosts: reachable
  gather_facts: no
  community.windows.win_mapped_drive:
    letter: Z
    state: absent
