---
- name: Check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping hosts
      win_ping:
      register: ping_result
      ignore_errors: yes

    - name: Group by reachable hosts
      group_by:
        key: reachable
      when: ping_result is success


- name: Ausführen von H-Inventory auf Windows-Servern 
  hosts: reachable
  gather_facts: no
  tasks:
    - name: Wechsel in Share und führe scan.bat aus
      win_shell: |
        cd \\ptmvm02\Deployment\hinventoryWindows
        cscript \\ptmvm02\Deployment\hinventoryWindows\hinventoryWindows.vbs /v /t 127.0.0.1
