---
- hosts: all
  gather_facts: no
  tasks:
  - name: Check CPU usage
    win_shell: |
      $localCPUs = (Get-WmiObject -Class Win32_ComputerSystem).NumberOfLogicalProcessors

      $totalVMCPUs = 0

      if (Get-Command -Name Get-VM -ErrorAction SilentlyContinue) {
          $VMs = Get-VM

          foreach ($VM in $VMs) {
              $totalVMCPUs += $VM.ProcessorCount
          }
      }

      $output = "Anzahl der lokalen logischen CPUs: " + $localCPUs + "`n" +
                "Anzahl der CPUs, die von Hyper-V VMs verwendet werden: " + $totalVMCPUs + "`n"

      if ($totalVMCPUs -gt $localCPUs) {
          $output += "Die Anzahl der CPUs, die von den VMs verwendet werden, überschreitet die Anzahl der lokalen CPUs!"
      } else {
          $output += "Die Anzahl der CPUs, die von den VMs verwendet werden, überschreitet NICHT die Anzahl der lokalen CPUs."
      }

      $output
    register: shell_output

  - name: Show output
    debug:
      msg: "{{ shell_output.stdout_lines }}"
