---
- name: Check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping hosts
      win_ping:
      register: ping_result
      ignore_errors: yes

    - name: Group by reachable hosts
      group_by:
        key: reachable
      when: ping_result is success
      
- name: Test windows whoami
  hosts: reachable
  strategy: free
  tasks:
   - name: windows whoami command
     win_command: whoami
     register: whoami
   - debug: var=whoami
