---
- name: Display toast message on reachable hosts
  hosts: all
  vars:
    deployment_start_time: "20:00 Uhr"
  gather_facts: no
  tasks:
    - name: Test
      community.windows.win_toast:
        expire: 60
        title: System Upgrade Notification
        msg: Automated upgrade about to start.  Please save your work and log off before {{ deployment_start_time }}
      async: 60
      poll: 0
...
