---
- name: Check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping hosts
      win_ping:
      register: ping_result
      ignore_errors: yes

    - name: Group by reachable hosts
      group_by:
        key: reachable
      when: ping_result is success
      
- name: Install .NET 6.0 on Windows
  hosts: reachable
  gather_facts: no
  tasks:
    - name: Download .NET 6.0 installer
      win_get_url:
        url: file:////ptmvm02/Deployment/CrowdSec/dotnet-runtime-6.0.16-win-x64.exe
        dest: C:\Temp\dotnet-runtime-6.0.16-win-x64.exe

    - name: Install .NET 6.0
      win_package:
        path: C:\Temp\dotnet-runtime-6.0.16-win-x64.exe
        #product_id: '{C71E93D2-B8B4-4858-B2A1-4C967DBC1C5F}'
        arguments:
        - --install
        - --quiet
        - --norestart
      # win_shell: |
      #   Start-Process -Wait -FilePath C:\Temp\dotnet-runtime-6.0.16-win-x64.exe -ArgumentList '/install /quiet /norestart'

    - name: Remove .NET 6.0 installer
      win_file:
        path: C:\Temp\dotnet-runtime-6.0.16-win-x64.exe
        state: absent

# - name: Enable Windows Defender Firewall logging
#   hosts: reachable
#   gather_facts: no
#   tasks:
#     - name: Set Windows Defender Firewall logging
#       win_shell: |
#         $settings = Get-NetFirewallProfile | Where-Object {$_.Name -eq "Domain" -or $_.Name -eq "Private" -or $_.Name -eq "Public"}
#         foreach ($profile in $settings) {
#           Set-NetFirewallProfile -Name $profile.Name -LogAllowed True
#           Set-NetFirewallProfile -Name $profile.Name -LogBlocked True
#         }
#       register: result
      
#     - debug:
#         var: result

- name: Install CrowdSec agent on Windows
  hosts: reachable
  gather_facts: no
  tasks:
    - name: Download CrowdSec installer
      win_get_url:
        url: file:////ptmvm02/Deployment/CrowdSec/crowdsec_1.5.1.msi
        dest: C:\temp\crowdsec_1.5.1.msi

    - name: Install CrowdSec agent
      #win_shell: C:\temp\crowdsec_1.5.1.msi /S
      win_package:
        path: C:\temp\crowdsec_1.5.1.msi
        product_id: '{7795C40F-5278-4AF6-B2FF-D2E7CACC678F}'
        state: present

- name: Install cs-windows-firewall-bouncer
  hosts: reachable
  gather_facts: no
  tasks:
    - name: Download cs-windows-firewall-bouncer MSI
      win_get_url:
        url: file:////ptmvm02/Deployment/CrowdSec/cs_windows_firewall_bouncer_setup.msi
        dest: C:\Temp\cs_windows_firewall_bouncer_setup.msi

    - name: Install cs-windows-firewall-bouncer
      #win_shell: C:\Temp\cs_windows_firewall_bouncer_setup.msi /S
      win_package:
        path: C:\Temp\cs_windows_firewall_bouncer_setup.msi
        product_id: '{C6F28E13-50FC-4D71-B6D9-B4C92C3CB6DB}'
        state: present

    - name: Remove cs-windows-firewall-bouncer MSI
      win_file:
        path: C:\Temp\cs_windows_firewall_bouncer_setup.msi
        state: absent 
...
