---
- name: WinPing
  hosts: all
  strategy: free
  gather_facts: no

  tasks:
  
  - name: Ping
    win_ping:
    async: 120 # Maximum allowed time in Seconds
    poll: 05 # Polling Interval in Seconds
