---
- name: Check reachable hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping hosts
      win_ping:
      register: ping_result
      ignore_errors: yes

    - name: Group by reachable hosts
      group_by:
        key: reachable
      when: ping_result is success
      
- name: Display toast message on reachable hosts
  hosts: reachable
  vars:
    deployment_start_time: "20:00 Uhr"
  gather_facts: no
  tasks:
    - name: Test
      community.windows.win_toast:
        expire: 60
        title: System Upgrade Notification
        msg: Automated upgrade about to start.  Please save your work and log off before {{ deployment_start_time }}
      async: 60
      poll: 0
...
