---
- name: Update and reboot Windows servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Update all packages
      ansible.windows.win_updates:
        category_names: 'all'
        log_path: 'c:\ansible_wu.txt'
      register: result

    - name: Reboot the server if necessary
      ansible.windows.win_reboot:
      when: result.reboot_required
...
